[project]
name = "pydantic-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "logfire>=4.9.0",
    "pydantic-ai[examples]>=1.0.10",
]
